--- 
env: 
  ARMTEMPLATELOCATION: ./LogicApp.json
  LOGICAPPNAME: testlogicappgithub
  PARAMETERSFILELOCATION: ./LogicApp.parameters.json
  RESOURCEGROUP: rajuchandramouli
  RESOURCEGROUPLOCATION: "East US"
jobs: 
  deploy-to-production: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout Repository"
        uses: actions/checkout@v2
      - 
        name: "Log In To Azure"
        uses: Azure/login@v1
        with: 
          creds: "${{secrets.AZURE_CREDENTIALS}}"
      - 
        name: "Validate Deployment"
        run: |
            az deployment group validate \
            --resource-group ${{env.RESOURCEGROUP}} \
            --mode Incremental \
            --template-file ${{env.ARMTEMPLATELOCATION}} \
            --parameters ${{env.PARAMETERSFILELOCATION}}
        shell: bash
      - 
        name: "Deploy Logic App"
        run: |
            az deployment group create \
            -g ${{env.RESOURCEGROUP}} \
            --template-file ${{env.ARMTEMPLATELOCATION}} \
            --parameters ${{env.PARAMETERSFILELOCATION}}
        shell: bash
      - 
        name: "Log Out From Azure"
        run: "az logout"
name: githubactionslogicapp-Deployment-Pipeline
true: 
  push: 
    branches: 
      - main

