# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
     # Checkout code
     -uses: actions/checkout@main

      # Log into Azure
    -uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

   #Name of the GitHub Action
name: Deploy testlogicappgithub

#Set the action on which the workflow will trigger
on:
 push:
   branches:
     - master

jobs:
  validate-and-deploy:
   runs-on: ubuntu-latest
   env:
     ENV_RESOURCEGROUP: rajuchandramouli
     ENV_RESOURCEGROUPLOCATION: East US

   steps:

    #Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@master
